/**
 * @file main.c
 * @author Damjan Belavic (damjan.belavic@vuka.hr)
 * @brief GlobalLogic Embedded Software Engineer in C / Task 1
 * @version 1.0
 * @date 2021-08-23
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include "sequence_detector/seq_detect.h"

const char *const TEST_INPUT_SEQUENCE[] = {
    "GabfdbLbsfbdRbasgOX",  // TRUE
    "AA4hfghdAAGLROX",      // TRUE
    "GLRObas832hXbasb",     // TRUE
    "GLROobiapjso83basb",   // FALSE (no X)
    "glroxbpoaijspoiasjdb", // FALSE (lower case)
    "GLpboiasjdbpoijOX"};   // FALSE (no R)

const char *const SEARCH_SEQUENCE = "GLROX";

uint8_t UART_RX_REG;

// ┌───────────────────────────────────────────────────────────────────────────┐
// │ Prototypes                                                                │
// └───────────────────────────────────────────────────────────────────────────┘

void serial_char_generator(uint8_t*);
char get_rand_ascii(void);


// ┌───────────────────────────────────────────────────────────────────────────┐
// │ Main                                                                      │
// └───────────────────────────────────────────────────────────────────────────┘

int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    srand(37); // Seed generated by fair d100 dice roll

    for (int n = 0; n < 80; n++)
    {
        char rand_char = get_rand_ascii();
        printf("%c", rand_char);
    }
    printf("\n\n");
    
    serial_char_generator(&UART_RX_REG);

    sequence_detector_init(SEARCH_SEQUENCE);

    return 0;
}

// ┌───────────────────────────────────────────────────────────────────────────┐
// │ Test related code                                                         │
// └───────────────────────────────────────────────────────────────────────────┘

void serial_char_generator(uint8_t *buffer)
{
    *buffer = get_rand_ascii();
}

/**
 * @brief Generates ASCII character limited to Base64 range
 * 
 * @return char Base64 ASCII character
 */
char get_rand_ascii(void)
{
    char rand_char;
    for (;;)
    {
        rand_char = rand() % 128;

        switch (rand_char)
        {
        case '+':
        case '/':
        case '0' ... '9':
        case 'A' ... 'Z':
        case 'a' ... 'z':
            return rand_char;
        default:
            break;
        }
    }
}
