/**
 * @file main.c
 * @author Damjan Belavic (damjan.belavic@vuka.hr)
 * @brief GlobalLogic Embedded Software Engineer in C / Task 1
 * @version 1.0
 * @date 2021-08-23
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <event2/event.h>
#include "sequence_detector/detector.h"

// ┌───────────────────────────────────────────────────────────────────────────┐
// │ CONSTANTS                                                                   │
// └───────────────────────────────────────────────────────────────────────────┘

const char *const TEST_INPUT_SEQUENCE[] = {
    "GabfdbLbsfbdRbasgOX",  // TRUE
    "AA4hfghdAAGLROX",      // TRUE
    "GLRObas832hXbasb",     // TRUE
    "GLROobiapjso83basb",   // FALSE (no X)
    "glroxbpoaijspoiasjdb", // FALSE (lower case)
    "GLpboiasjdbpoijOX"};   // FALSE (no R)

const char *const SEARCH_SEQUENCE = "GLROX";

// ┌───────────────────────────────────────────────────────────────────────────┐
// │ Enums, Variables, Structures, Typedefs                                    │
// └───────────────────────────────────────────────────────────────────────────┘

struct event_base *ev_base;
struct event *ticker_event, *timeout_event;
struct timeval delay_100ms = {0, 100000};
struct timeval delay_2000ms = {2, 0};

// ┌───────────────────────────────────────────────────────────────────────────┐
// │ Prototypes                                                                │
// └───────────────────────────────────────────────────────────────────────────┘

void ticker(int, short, void*);
char get_rand_ascii(void);

// ┌───────────────────────────────────────────────────────────────────────────┐
// │ Main                                                                      │
// └───────────────────────────────────────────────────────────────────────────┘

int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    srand(37); // Seed generated by fair d100 dice roll

    for (int row = 0; row < 16; row++)
    {
        for (int column = 0; column < 16; column++)
        {
            char rand_char = get_rand_ascii();
            printf("%c", rand_char);
        }
        printf("\n");
    }

    detector_init(SEARCH_SEQUENCE, timeout_event, );

    ev_base = event_base_new();
    ticker_event = event_new(ev_base, -1, EV_PERSIST, &ticker, NULL);
    event_add(ticker_event, &delay_100ms);
    event_base_dispatch(ev_base);
    
    return 0;
}

// ┌───────────────────────────────────────────────────────────────────────────┐
// │ Test related code                                                         │
// └───────────────────────────────────────────────────────────────────────────┘

void ticker(int fd, short event, void *arg)
{
    (void)fd;
    (void)event;
    (void)arg;

    char rand_char = get_rand_ascii();
    Process(rand_char);

}

/**
 * @brief Generates ASCII character limited to Base64 range
 * 
 * @return char Base64 ASCII character
 */
char get_rand_ascii(void)
{
    char rand_char;
    for (;;)
    {
        rand_char = rand() % 128;

        switch (rand_char)
        {
        case '+':
        case '/':
        case '0' ... '9':
        case 'A' ... 'Z':
        case 'a' ... 'z':
            return rand_char;
        default:
            break;
        }
    }
}
